apiVersion: v1
kind: Secret
metadata:
    name: {{ include "ark-samba.fullname" . }}
    labels:
        {{- include "ark-samba.labels" . | nindent 4 }}
type: Opaque
stringData:
    {{- if not .Values.ldap.externalHost.enabled }}
    domain:
        realm: {{ required "A default LDAP realm name is required" .Values.domain.realm | quote }}
        name: {{ required "A default LDAP domain name is required" .Values.domain.name | quote }}
        password: {{ required "A default domain password is required" .Values.domain.password | quote }}
    {{- end }}
