apiVersion: v1
kind: Service
metadata:
  name: {{ include "ark-samba.fullname" . }}
  labels:
    {{- include "ark-samba.labels" . | nindent 4 }}
spec:
  type: {{ .Values.serviceType }}
  clusterIP: None
  ports:
    {{- if .Values.ports.ldaps }}
    - port: {{ .Values.ports.ldaps }}
      targetPort: {{ .Values.ports.ldaps }}
      protocol: TCP
      name: ldaps
    {{- end }}
  selector:
    {{- include "ark-samba.selectorLabels" . | nindent 4 }}
